llama:
  model_path: /xdisk/bethard/kbozler/assets/gguf-models/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf
  ctx: 4096
  n_gpu_layers: -1
  n_threads: 8
  max_tokens: 256
  temperature: 0.1
  top_p: 0.9
  seed: 0

qwen:
  model_path: /xdisk/bethard/kbozler/assets/gguf-models/Qwen3-8B-Q4_K_M.gguf
  ctx: 8192
  n_gpu_layers: -1
  n_threads: 8
  max_tokens: 2048
  temperature: 0.0
  top_p: 0.9
  seed: 0
  stop:
    - "<|im_end|>"
  no_think: true

aya:
  model_path: /xdisk/bethard/kbozler/assets/gguf-models/aya-expanse-8b-Q4_K_M.gguf
  ctx: 8192
  n_gpu_layers: -1
  n_threads: 8
  max_tokens: 2048
  temperature: 0.0
  top_p: 1.0
  seed: 0